/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 16-Jan-2020 6:06:47 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Task` CASCADE
;

/* Create Tables */

CREATE TABLE `Task`
(
	`taskID` INT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(50) NOT NULL,
	`description` VARCHAR(100) NOT NULL,
	`color` INT NOT NULL,
	`state` VARCHAR(50) NOT NULL DEFAULT "activo",
	CONSTRAINT `taskID` PRIMARY KEY (`taskID` ASC)
)

;

SET FOREIGN_KEY_CHECKS=1
; 
